import streamlit as st
import os
import cyvcf2
import tempfile
from rag_agent import analyze_variant

# --- Page Config ---
st.set_page_config(page_title="ClinGen-AI", page_icon="🧬", layout="wide")

# --- Sidebar ---
with st.sidebar:
    st.image("https://img.icons8.com/color/96/dna-helix.png", width=80)
    st.title("ClinGen-AI")
    st.markdown("### 🏥 AI for Precision Medicine")
    st.info("This tool uses RAG (Retrieval-Augmented Generation) to interpret genomic variants from VCF files.")
    
    st.markdown("---")
    st.markdown("**Powered by:**")
    st.markdown("- 🦙 Llama 3 (Local)")
    st.markdown("- 🧬 BioPython")
    st.markdown("- 🦜 LangChain")

# --- Main Page ---
st.title("🧬 Genomic Variant Analysis Dashboard")
st.markdown("Upload a raw **.vcf** file to generate a clinical assessment report.")

uploaded_file = st.file_uploader("Upload VCF File", type=["vcf"])

if uploaded_file is not None:
    # Save uploaded file to a temporary location so cyvcf2 can read it
    tfile = tempfile.NamedTemporaryFile(delete=False, suffix=".vcf")
    tfile.write(uploaded_file.getvalue())
    tfile.close() # Close so other processes can access it
    
    st.success("File uploaded successfully! Analyzing variants...")
    
    # --- Processing ---
    vcf_reader = cyvcf2.VCF(tfile.name)
    
    # Create a container for the results
    results_container = st.container()
    
    with results_container:
        count = 0
        for variant in vcf_reader:
            # OPTIONAL: Filter for only high-quality variants or specific genes
            # For demo purposes, we limit to the first 2 variants to save time
            if count >= 2: 
                break
                
            if variant.QUAL and variant.QUAL > 50:
                count += 1
                
                # Format Variant Name
                variant_name = f"chr{variant.CHROM}:{variant.POS} ({variant.REF}>{variant.ALT[0]})"
                
                with st.expander(f"🔍 Analysis: {variant_name}", expanded=True):
                    col1, col2 = st.columns([1, 2])
                    
                    with col1:
                        st.subheader("Variant Details")
                        st.code(f"""
                        Chrom: {variant.CHROM}
                        Pos:   {variant.POS}
                        Ref:   {variant.REF}
                        Alt:   {variant.ALT[0]}
                        Qual:  {variant.QUAL}
                        """)
                    
                    with col2:
                        st.subheader("🤖 AI Clinical Report")
                        with st.spinner(f"Consulting Medical Knowledge Base for {variant_name}..."):
                            # Call our RAG Agent
                            query = f"Variant on Chromosome {variant.CHROM} at position {variant.POS}. Ref: {variant.REF}, Alt: {variant.ALT[0]}."
                            report = analyze_variant(query)
                            
                            st.write(report)
                            st.caption("ℹ️ Generated by Llama 3 using local PubMed embeddings.")
                            
    os.unlink(tfile.name) # Cleanup temp file